version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - .:/usr/src/fitness/
        ports:
            - "8080:8080"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://localhost:6379/0
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A fitness worker -l INFO
        volumes:
            - .:/usr/src/fitness
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=fitnessdb
            - POSTGRES_USER=djangouser
            - POSTGRES_PASSWORD=password
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"

volumes:
    pgdata: