#version: '3'
#
#services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: fitnessdb
#      POSTGRES_USER: djangouser
#      POSTGRES_PASSWORD: password
#
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8080
#    volumes:
#      - .:/fitness
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/fitness
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8080"

    environment:
          DATABASE_NAME: fitnessdb
          DATABASE_USER_NAME: djangouser
          DATABASE_USER_PASSWORD: password
          DATABASE_HOST: localhost
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=fitnessdb
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"