version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: fitnessdb
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/fitness
    ports:
      - "8080:8080"
    depends_on:
      - db