# Generated by Django 5.0.4 on 2024-09-12 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFitnessVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('data_start', models.DateTimeField(verbose_name='data_start')),
                ('data_finish', models.DateTimeField(verbose_name='data_finish')),
                ('promo_code', models.TextField(blank=True, verbose_name='promo_code')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('sub_type', models.CharField(blank=True, choices=[('type_00', 'type_00'), ('type_01', 'type_01'), ('type_02', 'type_02'), ('type_03', 'type_03')], max_length=10, verbose_name='sub_type')),
                ('phone_number', models.CharField(blank=True, unique=True, verbose_name='phone_number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'subscription_fit_videos',
                'verbose_name_plural': 'subscription_fit_video',
            },
        ),
    ]
