# Generated by Django 5.0.4 on 2024-09-12 15:29

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionfitnessvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfitnessvideo',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, unique=True, verbose_name='phone_number'),
        ),
    ]
