# Generated by Django 5.0.4 on 2024-09-12 15:32

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscriptionfitnessvideo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfitnessvideo',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='phone_number'),
        ),
    ]
