# Generated by Django 4.1.7 on 2023-03-17 11:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('about', models.TextField(verbose_name='about')),
                ('video', embed_video.fields.EmbedVideoField(verbose_name='video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('types', models.CharField(max_length=200, verbose_name='types')),
                ('trainer', models.CharField(blank=True, choices=[('Simona Soloduha', 'Simona Soloduha'), ('Анна Куркурина', 'Анна Куркурина'), ('Christa DiPaolo', 'Christa DiPaolo'), ('Pamela Reif', 'Pamela Reif'), ('Kelly Gale', 'Kelly Gale'), ('Анна Куркурина', 'Анна Куркурина'), ('Marnie Alton', 'Marnie Alton')], max_length=30, verbose_name='trainer')),
            ],
            options={
                'verbose_name_plural': 'FitVideos',
            },
        ),
    ]
