# Generated by Django 4.1.7 on 2023-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_fitvideo_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitvideo',
            name='times',
            field=models.CharField(blank=True, choices=[('5', 5), ('10', 10), ('15', 15), ('20', 20), ('25', 25), ('30', 30), ('35', 35), ('40', 40), ('45', 45), ('50', 50), ('55', 55), ('60', 60)], max_length=2, verbose_name='times'),
        ),
    ]
