# Generated by Django 4.1.7 on 2023-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_fitvideo_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitvideo',
            name='body_parts',
            field=models.CharField(blank=True, max_length=200, verbose_name='body_parts'),
        ),
        migrations.AlterField(
            model_name='fitvideo',
            name='trainer',
            field=models.CharField(blank=True, choices=[('Simona Soloduha', 'Simona Soloduha'), ('Christa DiPaolo', 'Christa DiPaolo'), ('Pamela Reif', 'Pamela Reif'), ('Kelly Gale', 'Kelly Gale'), ('Анна Куркурина', 'Анна Куркурина'), ('Marnie Alton', 'Marnie Alton')], max_length=30, verbose_name='trainer'),
        ),
        migrations.AlterField(
            model_name='fitvideo',
            name='types',
            field=models.CharField(blank=True, max_length=200, verbose_name='types'),
        ),
    ]
