# Generated by Django 4.1.7 on 2023-03-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_fitvideo_body_parts_alter_fitvideo_trainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('foto', models.ImageField(upload_to='static/trainers')),
            ],
            options={
                'verbose_name_plural': 'Trainers',
            },
        ),
        migrations.AlterField(
            model_name='fitvideo',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='video.trainer', verbose_name='trainer'),
        ),
    ]
