# Generated by Django 4.1.7 on 2023-03-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_trainer_alter_fitvideo_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='last_name'),
        ),
    ]
