# Generated by Django 4.1.7 on 2023-03-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_trainer_name_trainer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitvideo',
            name='free',
            field=models.BooleanField(default=True, verbose_name='free'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('free', models.BooleanField(default=True, verbose_name='free')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('fr_evening', models.ManyToManyField(null=True, related_name='fr_evening', to='video.fitvideo', verbose_name='fr_evening')),
                ('fr_morning', models.ManyToManyField(null=True, related_name='fr_morning', to='video.fitvideo', verbose_name='fr_morning')),
                ('mo_evening', models.ManyToManyField(null=True, related_name='mo_evening', to='video.fitvideo', verbose_name='mo_evening')),
                ('mo_morning', models.ManyToManyField(null=True, related_name='mo_morning', to='video.fitvideo', verbose_name='mo_morning')),
                ('sa_evening', models.ManyToManyField(null=True, related_name='sa_evening', to='video.fitvideo', verbose_name='sa_evening')),
                ('sa_morning', models.ManyToManyField(null=True, related_name='sa_morning', to='video.fitvideo', verbose_name='sa_morning')),
                ('su_evening', models.ManyToManyField(null=True, related_name='su_evening', to='video.fitvideo', verbose_name='su_evening')),
                ('su_morning', models.ManyToManyField(null=True, related_name='su_morning', to='video.fitvideo', verbose_name='su_morning')),
                ('th_evening', models.ManyToManyField(null=True, related_name='th_evening', to='video.fitvideo', verbose_name='th_evening')),
                ('th_morning', models.ManyToManyField(null=True, related_name='th_morning', to='video.fitvideo', verbose_name='th_morning')),
                ('to_evening', models.ManyToManyField(null=True, related_name='to_evening', to='video.fitvideo', verbose_name='to_evening')),
                ('to_morning', models.ManyToManyField(null=True, related_name='to_morning', to='video.fitvideo', verbose_name='to_morning')),
                ('we_evening', models.ManyToManyField(null=True, related_name='we_evening', to='video.fitvideo', verbose_name='we_evening')),
                ('we_morning', models.ManyToManyField(null=True, related_name='we_morning', to='video.fitvideo', verbose_name='we_morning')),
            ],
            options={
                'verbose_name_plural': 'Timetables',
            },
        ),
    ]
