# Generated by Django 4.1.7 on 2023-03-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_timetable_fr_evening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/video'),
        ),
    ]
