# Generated by Django 4.1.7 on 2023-03-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_fitvideo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='su_evening',
            field=models.ManyToManyField(blank=True, related_name='su_evening', to='video.fitvideo', verbose_name='su_evening'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='su_morning',
            field=models.ManyToManyField(blank=True, related_name='su_morning', to='video.fitvideo', verbose_name='su_morning'),
        ),
    ]
