# Generated by Django 4.1.7 on 2023-03-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_alter_timetable_su_evening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='fr_evening',
            field=models.ManyToManyField(blank=True, related_name='fr_evening', to='video.fitvideo', verbose_name='fr_evening'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fr_morning',
            field=models.ManyToManyField(blank=True, related_name='fr_morning', to='video.fitvideo', verbose_name='fr_morning'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mo_evening',
            field=models.ManyToManyField(blank=True, related_name='mo_evening', to='video.fitvideo', verbose_name='mo_evening'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mo_morning',
            field=models.ManyToManyField(blank=True, related_name='mo_morning', to='video.fitvideo', verbose_name='mo_morning'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sa_evening',
            field=models.ManyToManyField(blank=True, related_name='sa_evening', to='video.fitvideo', verbose_name='sa_evening'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sa_morning',
            field=models.ManyToManyField(blank=True, related_name='sa_morning', to='video.fitvideo', verbose_name='sa_morning'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='th_evening',
            field=models.ManyToManyField(blank=True, related_name='th_evening', to='video.fitvideo', verbose_name='th_evening'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='th_morning',
            field=models.ManyToManyField(blank=True, related_name='th_morning', to='video.fitvideo', verbose_name='th_morning'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='to_evening',
            field=models.ManyToManyField(blank=True, related_name='to_evening', to='video.fitvideo', verbose_name='to_evening'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='to_morning',
            field=models.ManyToManyField(blank=True, related_name='to_morning', to='video.fitvideo', verbose_name='to_morning'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='we_evening',
            field=models.ManyToManyField(blank=True, related_name='we_evening', to='video.fitvideo', verbose_name='we_evening'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='we_morning',
            field=models.ManyToManyField(blank=True, related_name='we_morning', to='video.fitvideo', verbose_name='we_morning'),
        ),
    ]
