# Generated by Django 4.1.7 on 2023-03-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_timetable_fr_evening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/video_img'),
        ),
    ]
